config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"   #Sets the products index page as the root 
  resources :products         #Sets up all the default routes for the products controller
  get '/payments/success', to: 'orders#success'     #Route to the successful payment page
  post '/payments/webhook', to: 'orders#webhook'    #Post method for the webhook from the Stripe session
  get '/orders', to: 'orders#index', as: 'orders'   #Route for purchase history
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
  has_many :orders
  validates :name, :price, :location, :description, :size, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhook]
  before_action :set_product, only: [:create]

  def index
    @orders = Order.all
    @products = Product.all
  end

  def edit
  end

  def new
    @order = Order.new
  end

  def show
  end

  def create
    @order = current_user.orders.new(order_params)
    if @order.save
      redirect_to @order
    else
      render :new
    end
  end

  def success
    @product = Product.find(params[:product_id])
  end

  def webhook
    payment_intent_id = params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_intent_id)
    product_id = payment.metadata.product_id
    user_id = payment.metadata.user_id
    Order.create(user_id: user_id, product_id: product_id)
  end

  private     #private means that the following methods are only used in this controller.

  def set_product
    @product = Product.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:order_id, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]   #Ensures that the user needs to be logged in to be able to create a new product or edit an existing one.
  before_action :set_product, only: [:show, :edit, :update, :destroy] #Determines the product for the show, edit, update and destroy methods.

  def index
    #Uses eager loading to get all the products in the Product model.
    @products = Product.all.includes(:user).with_attached_picture
  end

  #Goes to edit.html.erb to edit an existing product. (/product/:id/edit)
  def edit
  end

  #Creates a new product in the Product Model
  def new
    @product = Product.new
  end

  def show
    stripe_session = Stripe::Checkout::Session.create(               #Creating a stripe session.
      payment_method_types: ['card'],                                #Creates the payment method options. I'm only allowing card payments.
      client_reference_id: current_user ? current_user.id : nil,     #Sets the client reference id for stripe to the id of the user if there is a user logged in.
      customer_email: current_user ? current_user.email : nil,       #Sets the email for stripe to the email of the user if there is a user logged in.
      line_items:[{ 
        amount: (@product.price * 100).to_i,       #Stripe only deals in cents, so the product price needs to be converted to cents and made into an integer.
        name: @product.name,                   #Adds the product name to the payment
        description: @product.description,      #Adds the product description to the payment
        currency: 'aud',                        #Sets the currency for the payment
        quantity: 1,                            #Sets the quantity of products for the payment
       }],
       payment_intent_data: { 
         metadata: { 
           product_id: @product.id,
           user_id: current_user ? current_user.id : nil
          }
        },
        success_url: "#{root_url}payments/success?product_id=#{@product.id}",   #Setting the url to go to if the payment is successful.
        cancel_url: "#{root_url}products"          #Setting the url to go to if the payment is cancelled.
    )
    @session_id = stripe_session.id
  end

  #The product is updated using the the params from the product_params method.
  def update
    if @product.update(product_params)
      redirect_to @product             #Once a product is updated the browser goes to the show page of the product.
    else
      render :edit
    end
  end

  #To Delete a Product
  def destroy
    @product.destroy
    flash[:alert] = 'Successfully Deleted'    #Displays a message to show the product has been deleted
    redirect_to products_path                 #Once the product is deleted the browser goes back to the main page.
  end

  #To create a new product
  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  private    #private means that the following methods are only used in this controller.

  def set_product
    @product = Product.find(params[:id])   #Sets the product instance variable to the product that is provide by the params.
  end

 
  def product_params
    params.require(:product).permit(:name, :price, :size, :location, :description, :picture)  #Allows which params are to be accepted for the product model.
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.new(review_params)
    if @review.save
      redirect_to @review
    else
      render :new
    end
  end

  private   #private means that the following methods are only used in this controller.

  def set_product
    @product = Product.find(params[:id])
  end
  
  def review_params
    params.require(:review).permit(:score, :description, :product_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backyard Honey</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>
  

app/views/orders/index.html.erb
<h1>Purchased Items</h1>

<%# The map method is used to go through all the orders and make an array of any order that belongs to the current user%>
<% orders = @orders.map do |order| %> 
  <% if order.user_id == current_user.id%>   <%#Comparing the user id on the order to the id of the current user%>
    <% order.product_id %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
  <%#Each method is used to find all the products that have an id that matches the product id of the orders from the current user%>
    <% @products.each do |product| %>
      <% if orders.include?(product.id)  %> 
      <div class ="card-body">
        <div class="card" style="width: 18rem;">
          <% if product.picture.attached? %>     <%#Checks if the product has an image attached to it.%> 
            <%= image_tag product.picture, class: "card-img-top"%>  <%#If an image is attached it is shown on the card %>  
          <% else %>
            <%= image_tag "honeyjar.jpg", class: "card-img-top"%>   <%#If no image is attached, a default one from assets/images is used.%>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>         <%#Displays the product name on the card.%>
            <p class="card-text">Price: <%= number_to_currency(product.price) %></p>          <%#Displays the price on the card.%>
            <p class="card-text">Location: <%= product.location %></p>       <%#Displays the location on the card.%>
            <p class="card-text">Size: <%= product.size %></p>                   <%#Displays the product size on the card.%>
            <p class="card-text">Description: <%= product.description %></p>      <%#Displays the product description on the card.%>
            <%# <%= link_to "Write a Review", new_review_path, class:"nav-link btn-warning"%>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/orders/success.html.erb
<h1>Payment successful!</h1>     <%#Titles for the successful payment pages%>
<h1>Congratulations on your purchase!</h1>

<%#Displaying the card of the product that was purchased%>
<div class ="card-body">
<h1><%= @product.name %></h1>
<div class="card" style="width: 18rem;">
  <% if @product.picture.attached? %>
    <%= image_tag @product.picture, class: "card-img-top"%> 
  <% else %>
    <%= image_tag "honeyjar.jpg", class: "card-img-top"%>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= @product.name %></h5>
    <p class="card-text">Price: <%= number_to_currency(@product.price) %></p>
    <p class="card-text">Location: <%= @product.location %></p>
    <p class="card-text">Size: <%= @product.size %></p>
    <p class="card-text">Description: <%= @product.description %></p>
   </div>
</div>
</div>

app/views/products/edit.html.erb
<h1>Edit: <%= @product.name %></h1>

<%#The form to get user input for editing a product%>
<%= form_with model: @product do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>    <%#Input to receive an edit to the product name%>
    <br>
    <%= form.label :price %>
    <%= form.number_field :price, min: 0, max: 200%>  <%#The price can only be between $0 and $200%>
    <br>
    <%= form.label :size %>
    <%= form.number_field :size, min: 0, max: 2000 %>    <%#Input to change the product size. Can only be between 0 and 2000ml%>
    <br>
    <%= form.label :location %>
    <%= form.text_field :location %>    <%#Input to edit the product location%>
    <br>
    <%= form.label :description %>
    <%= form.text_area :description %>    <%#Input to edit the product description%>
    <br>
    <%= form.submit%>          <%#Button to submit the new information%>
<%end%>

app/views/products/index.html.erb
<h1><%= image_tag "honey-bee.png", class: "home-image"%>Backyard Honey</h1>
<div class="container">
  <div class="row">
  <%#Goes through each product in the Product model and shows in on the home page in a card%>
    <% @products.each do |product| %>
      <div class="col-md-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <% if product.picture.attached? %>   <%#Checks if the product has an image attached to it.%> 
              <%= image_tag product.picture, class: "card-img-top"%>    <%#If an image is attached it is shown on the card %>
            <% else %>
              <%= image_tag "honeyjar.jpg", class: "card-img-top"%>    <%#If no image is attached, a default one from assets/images is used.%>
            <% end %>
            <h5 class="card-title"><%= product.name %></h5>        <%#Displays the product name on the card.%>
            <p class="card-text">Price: <%= number_to_currency(product.price) %></p>       <%#Displays the price on the card.%>
            <p class="card-text">Location: <%= product.location %></p>           <%#Displays the location on the card.%>
            <p class="card-text">Size: <%= product.size %>ml</p>             <%#Displays the product size on the card.%>
            <%= link_to 'Show', product, class: "btn btn-warning"%>    <%#Button to go the show page of the product%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>Add a new Product</h1>
<div class="form">
<%= form_with model: @product do |form| %>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <br>
    <%= form.label :price %><br>
    <%= form.number_field :price, min: 0, max: 200%>
    <br>
    <%= form.label :size %><br>
    <%= form.number_field :size, min: 0, max: 2000, placeholder: "(ml)" %>
    <br>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
    <br>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <br>
    <%= form.label :picture %><br>
    <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg'%>
    <br><br>
    <%= form.submit%>
<%end%>
</div>

app/views/products/show.html.erb
<div class="show-page">
  <div class ="card-body">
    <h1><%= @product.name %></h1>
      <div class="card" style="width: 18rem;">
        <% if @product.picture.attached? %>          <%#Checks if the product has an image attached to it.%>
          <%= image_tag @product.picture, class: "card-img-top"%> <%#If an image is attached it is shown on the card %>
        <% else %>
          <%= image_tag "honeyjar.jpg", class: "card-img-top"%>    <%#If no image is attached, a default one from assets/images is used.%>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= @product.name %></h5>           <%#Displays the product name on the card.%>
          <p class="card-text">Price: <%= number_to_currency(@product.price) %></p>   <%#Displays the price on the card.%>
          <p class="card-text">Location: <%= @product.location %></p>       <%#Displays the location on the card.%>
          <p class="card-text">Size: <%= @product.size %></p>                <%#Displays the product size on the card.%>
          <p class="card-text">Description: <%= @product.description %></p>      <%#Displays the product description on the card.%>
          <% if current_user == @product.user %>   <%# Checks if the user owns the product%>
            <br>
            <%#Only shows delete and edit buttons if the user is the owner of the product.%>
            <button type="button" class="btn btn-warning"><%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            <br><br>
            <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_product_path(@product)%></button>
          <% else %>
            <%#Button to make a payment. Connects to stripe%>
            <%= button_tag "Buy",data: {stripe:'payment', session_id: @session_id, public_key: Rails.application.credentials.dig(:stripe, :public_key) }, id:'stripe-button', class:'btn btn-warning' %>
          <% end %>
        </div>
      </div>
  </div>
</div>

<%#Javascript for Stripe payment%>
<%= javascript_include_tag "https://js.stripe.com/v3/" %>
<%= javascript_pack_tag 'stripe' %>

app/views/reviews/new.html.erb
<h1>Write a Review for <%= "#{@product}" %></h1>
<div class="form">
<%#Form for creating a review  %>
<%= form_with model: @review do |form| %>
    <%= form.label :score %><br>
    <%= form.number_field :score, min: 0, max: 10%>    <%#Score can be between 0 and 10%>
    <br>

    <%= form.label :description %><br>
    <%= form.text_area :description %>   <%#Input for a description of the review%>
    <br>

    <br><br>
    <%= form.submit%>        <%#Button to submit the review information%>
<%end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand text-warning" href="/">Backyard Honey</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link text-warning" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? %>   <%#Checks if a user is signed in%>
        <li class="nav-item"> 
        <%#Button to go to the products/new page to add a new product if the user is signed in%>      
          <%= link_to "Sell Honey", new_product_path, class:"nav-link text-warning"%>
        </li>
        <li class="nav-item">
        <%#Button to go to orders/index page if the user is signed in. Shows all the purchase history.%>
          <%= link_to "Purchase History", orders_path, class:"nav-link text-warning"%>
        </li>
        <li class="nav-item">
        <%#Log out button to go to users/sign_out page if there is a user signed in%>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-link text-warning" %>
          <%else%>
          <%#Button to go to the users/sign_in page if no user is signed in%>
          <%= link_to "Sign In", new_user_session_path, class:"nav-link text-warning"%>
          <%#Button to go to the users/sign_up page if no user is signed in%>
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link text-warning"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>